baseurl = "http://www.schoolofdata.science"
languageCode = "en-us"
title = "School of Data"
canonifyUrls = "true"

[params]
    description = "For Those About to Science...We Salute You"
    custom_css = ["css/local.css"]

[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:schoolofdatasci@gmail.com"
